# Generated by Django 5.0.14 on 2026-03-31 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя клиента")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Телефон/Telegram"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("process", "В работе"),
                            ("completed", "Завершена"),
                            ("canceled", "Отмена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Источник (URL/Кампания)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заявки"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="catalog.vehicle",
                        verbose_name="Интересующий автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка (Лид)",
                "verbose_name_plural": "Заявки (Лиды)",
                "ordering": ["-created_at"],
            },
        ),
    ]
