# Generated by Django 5.1.15 on 2026-04-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="city",
            field=models.CharField(
                default="Не указан", max_length=120, verbose_name="Город"
            ),
        ),
    ]
