# Generated by Django 5.1.15 on 2026-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_inquiry_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="referer",
            field=models.CharField(blank=True, max_length=500, verbose_name="Referer"),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="Сессия"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="utm_campaign",
            field=models.CharField(
                blank=True, db_index=True, max_length=120, verbose_name="UTM Campaign"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="utm_medium",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="UTM Medium"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="utm_source",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="UTM Source"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="visitor_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="ID посетителя"
            ),
        ),
    ]
