# Generated by Django 5.2.17 on 2026-09-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_body_type_and_inquiry_phone_indexes"),
        ("leads", "0003_inquiry_referer_inquiry_session_key_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["phone", "created_at"], name="leads_inq_phone_created_idx"
            ),
        ),
    ]
