# Generated by Django 5.1.15 on 2026-04-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0013_vehicle_horsepower"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="ID посетителя"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="Сессия"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User-Agent"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Путь"
                    ),
                ),
                (
                    "referer",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Источник"
                    ),
                ),
                (
                    "is_vehicle_page",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Просмотр карточки авто",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_events",
                        to="catalog.vehicle",
                        verbose_name="Авто",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие посещения",
                "verbose_name_plural": "События посещений",
                "ordering": ["-created_at"],
            },
        ),
    ]
