# Generated by Django 5.1.15 on 2026-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitevent",
            name="utm_campaign",
            field=models.CharField(
                blank=True, db_index=True, max_length=120, verbose_name="UTM Campaign"
            ),
        ),
        migrations.AddField(
            model_name="visitevent",
            name="utm_medium",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="UTM Medium"
            ),
        ),
        migrations.AddField(
            model_name="visitevent",
            name="utm_source",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="UTM Source"
            ),
        ),
    ]
