"""
Major passenger-car brands on the Chinese market (for SEO directory seeding).

Curated list — not every sub-brand; extend in admin or edit this file + migrate.
"""

CHINA_CAR_BRANDS: tuple[str, ...] = (
    "Acura",
    "Aion",
    "AITO",
    "Arcfox",
    "Audi",
    "Avatr",
    "BAIC",
    "Baojun",
    "BAW",
    "BMW",
    "Buick",
    "BYD",
    "Cadillac",
    "Changan",
    "Chery",
    "Chevrolet",
    "Citroën",
    "Deepal",
    "Denza",
    "Dongfeng",
    "Exeed",
    "FAW",
    "Ford",
    "Forthing",
    "GAC",
    "Geely",
    "Genesis",
    "Geometry",
    "Great Wall",
    "Haima",
    "Haval",
    "Honda",
    "Hongqi",
    "Hyundai",
    "iCAR",
    "Infiniti",
    "JAC",
    "Jaecoo",
    "Jaguar",
    "Jeep",
    "Jetour",
    "Jetta",
    "Kaiyi",
    "Kia",
    "Land Rover",
    "Leapmotor",
    "Lexus",
    "Li Auto",
    "Lincoln",
    "Lynk & Co",
    "Maserati",
    "Maxus",
    "Mazda",
    "Mercedes-Benz",
    "MG",
    "Mini",
    "Mitsubishi",
    "Neta",
    "NIO",
    "Nissan",
    "Omoda",
    "Ora",
    "Peugeot",
    "Polestar",
    "Porsche",
    "Renault",
    "Roewe",
    "Seres",
    "Skoda",
    "Subaru",
    "Suzuki",
    "Tank",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "Voyah",
    "WEY",
    "Wuling",
    "Xiaomi",
    "XPeng",
    "Zeekr",
    "Zotye",
)
