# Generated by Django 5.0.14 on 2026-03-31 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Марка")),
                ("slug", models.SlugField(unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=catalog.models.brand_logo_path,
                        verbose_name="Логотип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Марка",
                "verbose_name_plural": "Марки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                ("slug", models.SlugField(help_text="Для SEO URL", unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InspectionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название отчета"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="catalog/inspection_reports/",
                        verbose_name="PDF отчет",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Отчет об осмотре",
                "verbose_name_plural": "Отчеты об осмотре",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Напр: Zeekr 001 2024 FR",
                        max_length=255,
                        verbose_name="Заголовок объявления",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "price_cny",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в CNY",
                    ),
                ),
                (
                    "price_rub",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Заполняется автоматически или вручную",
                        max_digits=15,
                        null=True,
                        verbose_name="Цена в RUB",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "specs",
                    models.JSONField(
                        default=dict,
                        help_text="Напр: {'power': '422 л.с.', 'range': '600 км'}",
                        verbose_name="Технические характеристики (ТТХ)",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to=catalog.models.vehicle_main_photo_path,
                        verbose_name="Основное фото",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="В ТОП"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="catalog.brand",
                        verbose_name="Марка",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.inspectionreport",
                        verbose_name="Цифровой отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=catalog.models.vehicle_photo_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок вывода"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="catalog.vehicle",
                        verbose_name="Автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото галереи",
                "verbose_name_plural": "Фото галереи",
                "ordering": ["order"],
            },
        ),
    ]
