# Generated by Django 5.0.14 on 2026-03-31 16:42

import django.core.validators
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_currency_fixed",
            field=models.BooleanField(default=False, verbose_name="Зафиксировать цену"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="mileage",
            field=models.PositiveIntegerField(default=0, verbose_name="Пробег (км)"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model",
            field=models.CharField(blank=True, max_length=100, verbose_name="Модель"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="year",
            field=models.PositiveIntegerField(default=0, verbose_name="Год выпуска"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, help_text="Для SEO URL", unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=catalog.models.vehicle_main_photo_path,
                verbose_name="Основное фото",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price_cny",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в CNY",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
