# Generated by Django 5.0.14 on 2026-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_vehicle_is_currency_fixed_vehicle_mileage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inspectionreport",
            options={
                "verbose_name": "Цифровой отчет",
                "verbose_name_plural": "Цифровые отчеты",
            },
        ),
        migrations.AddField(
            model_name="inspectionreport",
            name="dealer_verdict",
            field=models.TextField(blank=True, verbose_name="Вердикт дилера"),
        ),
        migrations.AddField(
            model_name="inspectionreport",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="Проверка пройдена"),
        ),
        migrations.AddField(
            model_name="inspectionreport",
            name="report_uid",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="UID отчета"
            ),
        ),
        migrations.AlterField(
            model_name="inspectionreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата осмотра"),
        ),
        migrations.AlterField(
            model_name="inspectionreport",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="catalog/inspection_reports/",
                verbose_name="PDF отчет (полный)",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionreport",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Название авто для отчета"
            ),
        ),
    ]
