# Generated by Django 5.0.14 on 2026-03-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_inspectionreport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="badge_text",
            field=models.CharField(
                blank=True,
                help_text="Бэйдж (В ПУТИ, АКЦИЯ...)",
                max_length=20,
                verbose_name="Текст на бэйдже",
            ),
        ),
    ]
