# Generated by Django 5.0.14 on 2026-04-05 21:31

from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_vehicle_badge_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionreport",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=catalog.models.inspection_report_path,
                verbose_name="PDF отчет (полный)",
            ),
        ),
    ]
