# Generated by Django 5.0.14 on 2026-04-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_inspectionreport_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="UID"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=200, verbose_name="Модель авто"),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год"
                    ),
                ),
                (
                    "horsepower",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Мощность (л.с.)"
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Пробег (км)"
                    ),
                ),
                (
                    "price_cny",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Цена CNY"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("images", models.JSONField(default=list, verbose_name="Фотографии")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
            ],
            options={
                "verbose_name": "Предложение дилера",
                "verbose_name_plural": "Предложения дилеров",
            },
        ),
    ]
