# Generated by Django 5.0.14 on 2026-04-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_dealeroffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="В ТОП"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="mileage",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Пробег (км)"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price_rub",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=0,
                help_text="Заполняется автоматически или вручную",
                max_digits=15,
                null=True,
                verbose_name="Цена в RUB",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Год выпуска"
            ),
        ),
    ]
