# Generated by Django 5.0.14 on 2026-04-12 03:49
# Index uses B-tree (not GIN on raw text) so PostgreSQL works without pg_trgm.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0008_alter_vehicle_is_featured_alter_vehicle_is_published_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="price_cny",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в CNY",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["description"], name="catalog_vehicle_desc_txt_idx"
            ),
        ),
    ]
