# Generated by Django 5.1.15 on 2026-04-18 09:22

import secrets

from django.db import migrations, models


def backfill_dealer_access_keys(apps, schema_editor):
    DealerOffer = apps.get_model("catalog", "DealerOffer")
    for offer in DealerOffer.objects.filter(access_key=""):
        offer.access_key = secrets.token_urlsafe(24)
        offer.save(update_fields=["access_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_vehicle_price_cny_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealeroffer",
            name="access_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Секрет для просмотра и скачивания; генерируется автоматически.",
                max_length=64,
                verbose_name="Ключ доступа",
            ),
        ),
        migrations.RunPython(backfill_dealer_access_keys, migrations.RunPython.noop),
    ]
