# Generated by Django 5.1.15 on 2026-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_dealeroffer_access_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="specs",
            field=models.JSONField(
                default=dict,
                help_text="Например: {'power': '422 л.с.', 'range': '600 км'}",
                verbose_name="Технические характеристики (ТТХ)",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="title",
            field=models.CharField(
                help_text="Например: Zeekr 001 2024 FR",
                max_length=255,
                verbose_name="Заголовок объявления",
            ),
        ),
    ]
