# Generated by Django 5.1.15 on 2026-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_vehicle_specs_alter_vehicle_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="body_type",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Тип кузова"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="color",
            field=models.CharField(blank=True, max_length=60, verbose_name="Цвет"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="transmission",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Коробка передач"
            ),
        ),
    ]
