# Generated by Django 5.1.15 on 2026-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_vehicle_body_type_vehicle_color_vehicle_transmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="horsepower",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Лошадиные силы (л.с.)"
            ),
        ),
    ]
