# Generated by Django 5.1.15 on 2026-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_vehicle_horsepower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price_rub',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, help_text='Цена для сайта в рублях', max_digits=15, null=True, verbose_name='Цена, ₽'),
        ),
    ]
