# Generated by Django 5.2.17 on 2026-08-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_security_pdf_and_drop_desc_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Свой текст плашки (если не «Новый» / «Выкупленные»). Например: В ПУТИ', max_length=20, verbose_name='Текст на бэйдже'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Показывать плашку «Выкупленные» и включать в фильтр выкупленных.', verbose_name='Выкупленный'),
        ),
    ]
