# Generated by Django 5.2.17 on 2026-08-17 13:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_refine_special_type_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="cny_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("12.48"),
                help_text="Рублей за 1 юань. Показывается под ценой на сайте.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Курс юаня",
            ),
        ),
    ]
