# Generated by Django 5.2.17 on 2026-08-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_vehicle_show_on_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="engine_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("petrol", "Бензин"),
                    ("electric", "Электрический"),
                    ("hybrid", "Гибрид"),
                ],
                db_index=True,
                help_text="Бензин, электрический или гибрид — для фильтра на сайте.",
                max_length=20,
                verbose_name="Тип двигателя",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["is_published", "engine_type"],
                name="catalog_veh_pub_engine_idx",
            ),
        ),
    ]
