# Generated by Django 5.2.17 on 2026-08-21 09:42

from django.db import migrations, models


def enable_home_for_published(apps, schema_editor):
    Vehicle = apps.get_model("catalog", "Vehicle")
    Vehicle.objects.filter(is_published=True, show_on_home=False).update(
        show_on_home=True
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_vehicle_engine_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="show_on_home",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Показывать в блоке на главной (нужно ещё «Опубликовано»). Снимите, если авто только в каталоге.",
                verbose_name="На главной",
            ),
        ),
        migrations.RunPython(enable_home_for_published, noop),
    ]
