# Generated by Django 5.2.17 on 2026-09-04 03:32

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_seed_china_car_brands"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="seo_landing_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Показывать на странице «Марки авто» и в sitemap, даже если сейчас нет объявлений в каталоге.",
                verbose_name="В справочнике марок (SEO)",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="badge_text",
            field=models.CharField(
                blank=True,
                help_text="Свой текст плашки (если не «Новые» / «Выкупленные»). Например: В ПУТИ",
                max_length=20,
                verbose_name="Текст на бэйдже",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="main_image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=catalog.models.vehicle_main_photo_path,
                verbose_name="Основное фото",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleimage",
            name="image",
            field=models.ImageField(
                max_length=255,
                upload_to=catalog.models.vehicle_photo_path,
                verbose_name="Изображение",
            ),
        ),
    ]
