# Generated by Django 5.2.17 on 2026-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_vehicle_image_path_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="avito_item_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Числовой ID или ссылка вида https://www.avito.ru/.../1234567890",
                null=True,
                verbose_name="ID объявления Авито",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="avito_price_sync_error",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Ошибка синхронизации Авито",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="avito_price_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Цена ушла на Авито"
            ),
        ),
    ]
