# Generated by Django 5.2.17 on 2026-09-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_vehicle_avito_price_sync"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["is_published", "body_type"], name="catalog_veh_pub_body_idx"
            ),
        ),
    ]
