# Generated by Django 5.2.17 on 2026-09-09 18:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_body_type_and_inquiry_phone_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRateSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manual_cny_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Рублей за 1 юань. Если заполнено — используется вместо ЦБ (удобно, когда сайт ЦБ недоступен).",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Ручной курс юаня",
                    ),
                ),
                (
                    "cbr_cny_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        editable=False,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Курс ЦБ (CNY)",
                    ),
                ),
                (
                    "cbr_fetched_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Курс ЦБ обновлён",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Курс юаня",
                "verbose_name_plural": "Курс юаня",
            },
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="cny_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("12.48"),
                help_text="Курс, с которым посчитана цена — показывается под ценой на сайте. Общий курс задаётся в разделе «Курс юаня».",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Курс юаня (на карточке)",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="is_currency_fixed",
            field=models.BooleanField(
                default=False,
                help_text="Включается автоматически, если юани не заданы.",
                verbose_name="Цена только в рублях",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price_cny",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                help_text="Если указана — рубли считаются автоматически по курсу сайта (ручной или ЦБ). Оставьте пустым, чтобы зафиксировать только рубли.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в CNY",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price_rub",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=0,
                help_text="Цена на сайте. При заполненной цене в юанях пересчитывается сама.",
                max_digits=15,
                null=True,
                verbose_name="Цена, ₽",
            ),
        ),
    ]
