# Generated by Django 5.2.17 on 2026-09-09 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_currency_rate_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="price_cny",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                help_text="Если указана — рубли считаются автоматически по курсу сайта (ручной или ЦБ). Оставьте пустым, чтобы зафиксировать только рубли.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена, ¥",
            ),
        ),
    ]
