# Generated by Django 5.2.17 on 2026-09-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_price_cny_verbose_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        db_index=True, max_length=80, verbose_name="Марка"
                    ),
                ),
                (
                    "brand_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Если заполнен — ссылка на страницу марки в каталоге.",
                        max_length=120,
                        verbose_name="Slug марки в каталоге",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Модель / комплектация"
                    ),
                ),
                ("price_rub", models.PositiveIntegerField(verbose_name="Цена от, ₽")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Показывать"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Позиция прайса",
                "verbose_name_plural": "Прайс «авто под заказ»",
                "ordering": ["sort_order", "brand", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title",), name="catalog_pricelistitem_title_uniq"
                    )
                ],
            },
        ),
    ]
