# Generated by Django 5.2.17 on 2026-09-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0036_load_price_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="rutube_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Ссылка на видео с Rutube (обычная или «код вставки»). На сайте откроется плеер Rutube — файл на сервер не заливается.",
                max_length=500,
                verbose_name="Видео Rutube",
            ),
        ),
    ]
