# Generated by Django 5.0.14 on 2026-03-31 16:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Заголовок статьи"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=250, unique=True, verbose_name="SEO Slug"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="До 160 символов",
                        verbose_name="SEO Описание (Мета)",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SEO Ключевые слова"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="articles/covers/", verbose_name="Обложка статьи"
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Содержимое статьи"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Статья (SEO)",
                "verbose_name_plural": "Статьи (SEO)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок вывода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос-ответ (FAQ)",
                "verbose_name_plural": "Вопросы-ответы (FAQ)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="Имя клиента"),
                ),
                (
                    "vehicle_purchased",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Купленное авто"
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий/Отзыв")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Рейтинг (1-5)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата отзыва"),
                ),
            ],
            options={
                "verbose_name": "Отзыв клиента",
                "verbose_name_plural": "Отзывы клиентов",
                "ordering": ["-date"],
            },
        ),
    ]
