# Generated by Django 5.0.14 on 2026-04-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Для превью в каталоге и блоге",
                verbose_name="Краткое описание",
            ),
        ),
    ]
