# Generated by Django 5.0.14 on 2026-04-05 21:31

from django.db import migrations, models


def article_cover_path(instance, filename):
    return f"articles/covers/{filename}"


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_article_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="main_image",
            field=models.ImageField(
                upload_to=article_cover_path,
                verbose_name="Обложка статьи",
            ),
        ),
    ]
