# Generated by Django 5.2.17 on 2026-08-09 05:38

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


def seed_platform_urls(apps, schema_editor):
    ReviewPlatformSettings = apps.get_model("content", "ReviewPlatformSettings")
    obj, _ = ReviewPlatformSettings.objects.get_or_create(pk=1)
    changed = False
    for field, setting_name in (
        ("yandex_url", "REVIEW_YANDEX_URL"),
        ("twogis_url", "REVIEW_2GIS_URL"),
        ("avito_url", "REVIEW_AVITO_URL"),
    ):
        if not getattr(obj, field):
            value = (getattr(settings, setting_name, "") or "").strip()
            if value:
                setattr(obj, field, value)
                changed = True
    if changed:
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_review_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewPlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yandex_url",
                    models.URLField(
                        blank=True,
                        help_text="Профиль или карточка организации в Яндекс Картах",
                        verbose_name="Ссылка на Яндекс Карты",
                    ),
                ),
                (
                    "twogis_url",
                    models.URLField(
                        blank=True,
                        help_text="Карточка организации в 2ГИС",
                        verbose_name="Ссылка на 2ГИС",
                    ),
                ),
                (
                    "avito_url",
                    models.URLField(
                        blank=True,
                        help_text="Профиль продавца или отзывы на Авито",
                        verbose_name="Ссылка на Авито",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Ссылки на отзывы",
                "verbose_name_plural": "Ссылки на отзывы",
            },
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="review",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Прямая ссылка на этот отзыв. Если пусто — берётся общая ссылка площадки.",
                verbose_name="Ссылка на отзыв",
            ),
        ),
        migrations.RunPython(seed_platform_urls, migrations.RunPython.noop),
    ]
