# Generated by Django 5.1.15 on 2026-08-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_review_platform_settings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
