# Generated by Django 5.2.17 on 2026-09-11 03:05

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_delete_article_and_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Заголовок")),
                (
                    "teaser",
                    models.CharField(
                        help_text="1–2 строки под баннером на главной.",
                        max_length=180,
                        verbose_name="Короткий текст",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=content.models.promo_banner_path,
                        verbose_name="Баннер",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        default="#leads-section",
                        help_text="Куда ведёт клик. Например #leads-section или /avto-pod-zakaz/.",
                        max_length=300,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["sort_order", "-updated_at"],
            },
        ),
    ]
