# Generated by Django 5.2.17 on 2026-09-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_fix_promo_banners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Прямая ссылка на этот отзыв. Если пусто — берётся общая ссылка площадки.",
                max_length=500,
                verbose_name="Ссылка на отзыв",
            ),
        ),
        migrations.AlterField(
            model_name="reviewplatformsettings",
            name="avito_url",
            field=models.URLField(
                blank=True,
                help_text="Профиль продавца или отзывы на Авито",
                max_length=500,
                verbose_name="Ссылка на Авито",
            ),
        ),
        migrations.AlterField(
            model_name="reviewplatformsettings",
            name="twogis_url",
            field=models.URLField(
                blank=True,
                help_text="Карточка организации в 2ГИС",
                max_length=500,
                verbose_name="Ссылка на 2ГИС",
            ),
        ),
        migrations.AlterField(
            model_name="reviewplatformsettings",
            name="yandex_url",
            field=models.URLField(
                blank=True,
                help_text="Профиль или карточка организации в Яндекс Картах",
                max_length=500,
                verbose_name="Ссылка на Яндекс Карты",
            ),
        ),
    ]
