# Generated by Django 5.2.17 on 2026-09-11 07:50

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_review_url_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Круглое фото клиента на карточке отзыва. Если пусто — показываются инициалы.",
                upload_to=content.models.review_avatar_path,
                verbose_name="Аватар",
            ),
        ),
    ]
