# Generated by Django 5.2.17 on 2026-09-11 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_review_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewplatformsettings",
            name="avito_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Число оценок на площадке. Пусто — считать по отзывам на сайте.",
                null=True,
                verbose_name="Оценок на Авито",
            ),
        ),
        migrations.AddField(
            model_name="reviewplatformsettings",
            name="avito_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Как на площадке. Пусто — считать по отзывам на сайте.",
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг Авито",
            ),
        ),
        migrations.AddField(
            model_name="reviewplatformsettings",
            name="twogis_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Число оценок на площадке. Пусто — считать по отзывам на сайте.",
                null=True,
                verbose_name="Оценок в 2ГИС",
            ),
        ),
        migrations.AddField(
            model_name="reviewplatformsettings",
            name="twogis_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Как на площадке (например 5.0). Пусто — считать по отзывам на сайте.",
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг 2ГИС",
            ),
        ),
        migrations.AddField(
            model_name="reviewplatformsettings",
            name="yandex_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Число оценок на площадке. Пусто — считать по отзывам на сайте.",
                null=True,
                verbose_name="Оценок в Яндекс Картах",
            ),
        ),
        migrations.AddField(
            model_name="reviewplatformsettings",
            name="yandex_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Как на площадке (например 5.0). Пусто — считать по отзывам на сайте.",
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг Яндекс Карт",
            ),
        ),
    ]
